.TH XYMONPAGE 1 "Version 4.3.15: 30 Jan 2014" "Xymon"
.SH NAME
xymonpage \- Utility to show a webpage using header and footer
.SH SYNOPSIS
.B "xymonpage [options]"

.SH DESCRIPTION
\fBxymonpage\fR is a tool to generate a webpage in the Xymon style,
with a standard header- and footer as well as a Xymon background.
The data to present on the webpage, apart from the header and
footer, are passed to xymonpage in stdin. The generated webpage
is printed to stdout.

.SH OPTIONS
.IP "--env=FILENAME"
Loads the environment defined in FILENAME before executing the CGI script.

.IP "--hffile=PREFIX"
Use the header- and footer-files in $XYMONHOME/web/PREFIX_header and PREFIX_footer.
If not specified, stdnormal_header and stdnormal_footer are used.

.IP "--color=COLOR"
Set the background color of the generated webpage to COLOR. Default: Blue

.IP "--debug"
Enable debugging output.

.SH "SEE ALSO"
xymon(7)

