#!/bin/bash

hg init scam
cd scam

#$ name: wife

cat > letter.txt <<EOF
Greetings!

I am Mariam Abacha, the wife of former
Nigerian dictator Sani Abacha.
EOF

hg add letter.txt
hg commit -m '419 scam, first draft'

#$ name: cousin

cd ..
hg clone scam scam-cousin
cd scam-cousin

cat > letter.txt <<EOF
Greetings!

I am Shehu Musa Abacha, cousin to the former
Nigerian dictator Sani Abacha.
EOF

hg commit -m '419 scam, with cousin'

#$ name: son

cd ..
hg clone scam scam-son
cd scam-son

cat > letter.txt <<EOF
Greetings!

I am Alhaji Abba Abacha, son of the former
Nigerian dictator Sani Abacha.
EOF

hg commit -m '419 scam, with son'

#$ name: pull

cd ..
hg clone scam-cousin scam-merge
cd scam-merge
hg pull -u ../scam-son

#$ name: merge
#$ ignore: [<>]{7} /tmp/.*

export HGMERGE=merge
hg merge
cat letter.txt

#$ name: commit

cat > letter.txt <<EOF
Greetings!

I am Bryan O'Sullivan, no relation of the former
Nigerian dictator Sani Abacha.
EOF

hg commit -m 'Send me your money'
hg tip
