.TH BBGEND_CHANNEL 8 "Version 3.4: 21 nov 2004" "bbgen toolkit"
.SH NAME
bbgend_channel \- Feed a bbgend channel to a worker module
.SH SYNOPSIS
.B "bbgend_channel --channel=CHANNEL [options] workerprogram [worker-options]"

.SH DESCRIPTION
bbgend_channel hooks into one of the 
.I bbgend(8)
channels that provide information about events occurring in the BB system.
It retrieves messages from the bbgend daemon, and passes them on to the
.I workerprogram
on the STDIN of the worker program. Worker programs can then handle
messages as they like.

A number of worker programs are shipped with bbgend, e.g.
.I bbgend_filestore(8),
.I bbgend_htmllog(8),
.I bbgend_history(8),
.I bbgend_alert(8),
.I bbgend_larrd(8)

If you want to write your own worker module, a sample worker module
is provided as part of the bbgend distribution in the bbgend_sample.c
file. This illustrates how to easily fetch and parse messages.

.SH OPTIONS
bbgend_channel accepts a few options.

.IP "--channel=CHANNELNAME"
Specifies the channel to receive messages from, only one channel can be used.
This option is required. The following channels are available:
.br
"status" receives all Big Brother status- and summary-messages
.br
"stachg" receives information about status changes
.br
"page" receives information about statuses triggering alerts
.br
"data" receives all Big Brother "data" messages
.br
"notes" receives all Big Brother "notes" messages
.br
"enadis" receives information about hosts being disabled or enabled.

.IP "--daemon"
bbgend_channel is normally started by 
.I bblaunch(8)
as a task defined in the
.I bbtasks.cfg(5)
file. If you are not using bblaunch, then starting bbgend_channel with this
option causes it to run as a stand-alone background task.

.IP "--pidfile=FILENAME"
If running as a stand-alone daemon, bbgend_channel will save the proces-ID 
of the daemon in FILENAME. This is useful for automated startup- and shutdown-
scripts.

.IP "--env=FILENAME"
Loads the environment variables defined in FILENAME before starting bbgend_channel.
This is normally used only when running as a stand-alone daemon; if bbgend_channel
is started by bblaunch, then the environment is controlled by the task definition 
in the
.I bbtasks.cfg(5)
file.

.IP "--debug"
Enable debugging output.

.SH FILES
This program does not use any configuration files.

.SH "SEE ALSO"
bbgen-intro(7), bbgend(8)

