.TH BBD_LARRD 8 "Version 3.2:  4 okt 2004" "bbgen toolkit"
.SH NAME
bbd_larrd \- bbgend worker module for updating LARRD graphs
.SH SYNOPSIS
.B "bbd_channel --channel=status bbd_larrd [options]"
.br
.B "bbd_channel --channel=data bbd_larrd [options]"

.SH DESCRIPTION
bbd_larrd is a worker module for bbgend, and as such it is normally
run via the
.I bbd_channel(8)
program. It receives "status" and "data" messages from bbgend via
stdin, and updates the LARRD graphs so you no longer need to bother
with installing LARRD on your BBDISPLAY server. It also eliminates
the need to store all status- and data-messages to disk, which is
necessary with the standard LARRD setup.

LARRD can send data to Big Brother using both status- and data-
messages. So You will probably need to run this module twice, once
for the "status" channel and once for the "data" channel.

.SH OPTIONS
.IP "--debug"
Enable debugging output.

.IP "--rrddir=DIRECTORY"
Defines the directory where the LARRD RRD-files are stored. bbd_larrd
will use the location pointed to by the BBRRDS environment is this
option is not present.

.SH ENVIRONMENT
.IP BBRRDS
Default directory where LARRD RRD files are stored.

.SH "SEE ALSO"
bbd_channel(8), bbgen-intro(7), bbgend(8)

