.TH BBGEND_FILESTORE 8 "Version 3.4: 21 nov 2004" "bbgen toolkit"
.SH NAME
bbgend_filestore \- bbgend worker module for storing Big Brother files
.SH SYNOPSIS
.B "bbgend_channel --channel=status bbgend_filestore --status [options]"
.br
.B "bbgend_channel --channel=data   bbgend_filestore --data [options]"
.br
.B "bbgend_channel --channel=notes  bbgend_filestore --notes [options]"
.br
.B "bbgend_channel --channel=enadis bbgend_filestore --enadis [options]"

.SH DESCRIPTION
bbgend_filestore is a worker module for bbgend, and as such it is normally
run via the
.I bbgend_channel(8)
program. It receives bbgend messages from a bbgend channel via stdin, and 
stores these in the filesystem in a manner that is compatible with the 
standard Big Brother daemon, bbd.

This program can be started multiple times, if you want to store
messages for more than one channel.

.SH OPTIONS
.IP "--status"
Incoming messages are "status" messages, they will be stored in the
$BBLOGS/ directory. If you are using 
.I bbgen(1)
throughout your Big Brother server, you will not need to run this
module to save status messages, unless you have a third-party 
Big Brother add-on that reads the status-logs directly.
This module is NOT needed for LARRD, you should run the 
.I bbgend_larrd(8)
module instead.

.IP "--data"
Incoming messages are "data" messages, they will be stored in the
$BBDATA directory. This module is not needed, unless you have a
third-party module that processes the data-files. This module is
NOT needed for LARRD, you should run the 
.I bbgend_larrd(8)
module instead.

.IP "--notes"
Incoming messages are "notes" messages, they will be stored in the
$BBNOTES directory. This modules is only needed if you want to 
allow people to remotely update the notes-files available on the
Big Brother webpages.

.IP "--enadis"
Incoming messages are enable/disable messages, they will update 
files in the $BBDISABLED directory. This is only needed if you have
third-party add-ons that use these files, e.g. the "maint.pl" script
for disabling or enabling hosts in Big Brother.

.IP "--dir=DIRECTORY"
Overrides the default output directory.

.IP "--htmldir=DIRECTORY"
When subscribing to the status channel, an HTML version of the logfile
is saved in this directory. This is for compatibility with the bbd 
daemon when BBLOGSTATUS is set to "static".

.IP "--htmlext=.EXT"
Set the filename extension for generated HTML files. By default, HTML
files are saved with a ".html" extension.

.IP "--only=test[,test,test]"
Save status messages only for the listed set of tests. This can be useful
if you have an external script that needs to parse some of the status logs,
but you do not want to save all status logs.

.IP "--debug"
Enable debugging output.

.SH FILES
This module does not rely on any configuration files.

.SH "SEE ALSO"
bbgend_channel(8), bbgend_larrd(8), bbgen-intro(7), bbgend(8)

