.TH BBD_FILESTORE 8 "Version 3.2:  4 okt 2004" "bbgen toolkit"
.SH NAME
bbd_filestore \- bbgend worker module for storing Big Brother files
.SH SYNOPSIS
.B "bbd_channel --channel=status bbd_filestore --status [options]"
.br
.B "bbd_channel --channel=data   bbd_filestore --data [options]"
.br
.B "bbd_channel --channel=notes  bbd_filestore --notes [options]"
.br
.B "bbd_channel --channel=enadis bbd_filestore --enadis [options]"

.SH DESCRIPTION
bbd_filestore is a worker module for bbgend, and as such it is normally
run via the
.I bbd_channel(8)
program. It receives bbgend messages from a bbgend channel via stdin, and 
stores these in the filesystem in a manner that is compatible with the 
standard Big Brother daemon, bbd.

This program can be started multiple times, if you want to store
messages for more than one channel.

.SH OPTIONS
.IP "--status"
Incoming messages are "status" messages, they will be stored in the
$BBLOGS/ directory. If you are using 
.I bbgen(1)
throughout your Big Brother server, you will not need to run this
module to save status messages, unless you have a third-party 
Big Brother add-on that reads the status-logs directly.
This module is NOT needed for LARRD, you should run the 
.I bbd_larrd(8)
module instead.

.IP "--data"
Incoming messages are "data" messages, they will be stored in the
$BBDATA directory. This module is not needed, unless you have a
third-party module that processes the data-files. This module is
NOT needed for LARRD, you should run the 
.I bbd_larrd(8)
module instead.

.IP "--notes"
Incoming messages are "notes" messages, they will be stored in the
$BBNOTES directory. This modules is only needed if you want to 
allow people to remotely update the notes-files available on the
Big Brother webpages.

.IP "--enadis"
Incoming messages are enable/disable messages, they will update 
files in the $BBDISABLED directory. This is only needed if you have
third-party add-ons that use these files, e.g. the "maint.pl" script
for disabling or enabling hosts in Big Brother.

.IP "--dir=DIRECTORY"
Overrides the default output directory.

.IP "--debug"
Enable debugging output.

.SH FILES
This module does not rely on any configuration files.

.SH "SEE ALSO"
bbd_channel(8), bbd_larrd(8), bbgen-intro(7), bbgend(8)

