.TH HOBBITD_ALERT 8 "Version 4.0.4: 29 May 2005" "Hobbit Monitor"
.SH NAME
hobbitd_alert \- hobbitd worker module for sending out alerts
.SH SYNOPSIS
.B "hobbitd_channel --channel=page hobbitd_alert [options]"

.SH DESCRIPTION
hobbitd_alert is a worker module for hobbitd, and as such it is normally
run via the
.I hobbitd_channel(8)
program. It receives hobbitd page- and ack-messages from the "page" 
channel via stdin, and uses these to send out alerts about failed 
and recovered hosts and services.

The operation of this module is controlled by the
.I hobbit-alerts.cfg(5)
file. This file holds the definition of rules and recipients,
that determine who gets alerts, how often, for what servers etc.

.SH OPTIONS
.IP "--config=FILENAME"
Sets the filename for the 
.I hobbit-alerts.cfg
file. The default value is "etc/hobbit-alerts.cfg" below the Hobbit
server directory.

.IP "--dump-config"
Dumps the configuration after parsing it. May be useful to track
down problems with configuration file errors.

.IP "--checkpoint-file=FILENAME"
File where the current state of the hobbitd_alert module is saved. 
When starting up, hobbitd_alert will also read this file to restore
the previous state.

.IP "--checkpoint-interval=N"
Defines how often (in seconds) the checkpoint-file is saved.

.IP "--cfid"
If this option is present, alert messages will include a line with
"cfid:N" where N is the linenumber in the hobbit-alerts.cfg file that
caused this message to be sent. This can be useful to track down
problems with duplicate alerts.

.IP "--test HOST SERVICE [duration [color [time]]]"
Shows which alert rules matches the given HOST/SERVICE combination.
Useful to debug configuration problems, and see what rules are used
for an alert. 

The "duration" parameter is the duration of the alert in seconds. 

The "color" parameter is the color of the alert. 

The "time" parameter is the time-of-day for the alert, expressed as an
absolute time in the epoch format (seconds since Jan 1 1970). This is
easily obtained with the GNU date utility using the "+%s" output format.


.IP "--debug"
Enable debugging output.

.SH ENVIRONMENT
.IP MAIL
The first part of a command line used to send out an e-mail with a 
subject, typically set to "/usr/bin/mail -s" . hobbitd_alert will add
the subject and the mail recipients to form the command line used
for sending out email alerts.

.IP MAILC
The first part of a command line used to send out an e-mail without
a subject. Typically this will be "/usr/bin/mail". hobbitd_alert will
add the mail recipients to form the command line used for sending
out email alerts.

.SH FILES
.IP "~hobbit/server/etc/hobbit-alerts.cfg"

.SH "SEE ALSO"
hobbit-alerts.cfg(5), hobbitd(8), hobbitd_channel(8), hobbit(7)

