.TH HOBBITD 8 "Version 3.4: 21 nov 2004" "bbgen toolkit"
.SH NAME
hobbitd \- Master network daemon for a Hobbit server
.SH SYNOPSIS
.B "hobbitd [options]"

.SH DESCRIPTION
hobbitd is a replacement for the bbd daemon from the Big
Brother package. It is designed for large BB installations,
and has a strong focus on being a high-speed, low-overhead 
implementation of a Big Brother server.

To achieve this, hobbitd stores all information about the state
of the monitored systems in memory, instead of storing it in
the host filesystem. A number of plug-ins can be enabled to
enhance the basic operation; e.g. a set of plugins are provided
to implement persistent storage in a way that is compatible 
with the standard Big Brother daemon. However, even with these
plugins enabled, hobbitd still performs much faster than the
standard bbd daemon.

hobbitd is normally started and controlled by the
.I hobbitlaunch(8)
tool, and the command used to invoke hobbitd should therefore be
in the hobbittasks.cfg file.

.SH OPTIONS
.IP "--bbhosts=FILENAME"
Specifies the path to the Big Brother bb-hosts file. This is used
to check if incoming status messages refer to known hosts; depending
on the "--ghosts" option, messages for unknown hosts may be dropped.
If this option is omitted, the default path used is set by the BBHOSTS
environment variable.

.IP "--checkpoint-file=FILENAME"
With regular intervals, hobbitd will dump all of its internal state 
to this check-point file. It is also dumped when hobbitd terminates,
or when it receives a SIGUSR1 signal.

.IP "--checkpoint-interval=N"
Specifies the interval (in seconds) between dumps to the check-point
file. The default is 900 seconds (15 minutes).

.IP "--restart=FILENAME"
Specifies an existing file containing a previously generated hobbitd 
checkpoint. When starting up, hobbitd will restore its internal state
from the information in this file. You can use the same filename for
"--checkpoint-file" and "--restart".

.IP "--alertcolors=COLOR[,COLOR]"
Specifies which colors should trigger an alert. Alerts are triggered
when a status changes from a non-alert color to an alert-color, or
vice verse. The 
.I hobbitd_alert(8)
module can then further filter alert events based on a separate alert
configuration, but you should still list the possible alert colors here.
The default setting is "--alertcolors=red,yellow,purple".

.IP "--ghosts={allow|drop|log}"
How to handle status messages from unknown hosts. The "allow" setting
accepts all status messages, regardless of whether the host is known
in the bb-hosts file or not. "drop" silently ignores reports from unknown 
hosts. "log" works like drop, but logs the event in the hobbitd output file.
The default is "allow", unless the BBGHOSTS environment variable is set.

.IP "--no-purple"
Prevent status messages from going purple when they are no longer valid.
Unlike the standard bbd daemon, purple-handling is done by hobbitd.

.IP "--purple-conn=CONNTESTCOLUMN"
When a host goes down that has the BB client installed, you will often
get alerts both from the network test (ping) and from the client tests
when they go purple because they are no longer being updated. With this
option you can tell hobbitd which test is the "ping" test; when this test
is red and some other test for the same host should go purple, then
hobbitd will instead make it go "clear". Since a "clear" status does not
trigger any alarms, you avoid getting many alarms for purple hosts.

.IP "--listen=IP[:PORT]"
Specifies the IP-address and port where hobbitd will listen for incoming
connections. By default, hobbitd listens on IP 0.0.0.0 (i.e. all IP-
adresses available on the host) and port 1984.

.IP "--daemon"
hobbitd is normally started by 
.I hobbitlaunch(8).
If you do not want to use hobbitlaunch, you can start hobbitd with this option;
it will then detach from the terminal and continue running as a background
task.

.IP "--env=FILENAME"
Loads the content of FILENAME as environment settings before starting
hobbitd. This is mostly used when running as a stand-alone daemon; if
hobbitd is started by hobbitlaunch, the environment settings are controlled
by the hobbitlaunch hobbittasks.cfg file.

.IP "--pidfile=FILENAME"
If hobbitd runs as a daemon process, the proces-ID of hobbitd will
be written to this file. This is for use in automated startup scripts.

.IP "--log=FILENAME"
Redirect all output from hobbitd to FILENAME.

.IP "--status-senders=IP[/MASK][,IP/MASK]"
Controls which hosts may send "status", "combo", "config" and "query"
commands to hobbitd.

By default, any host can send status-updates. If this option is used, 
then status-updates are accepted only if they are sent by one of the 
IP-adresses listed here, or if they are sent from the IP-address of the 
host that the updates pertains to (this is to allow BB clients to send in their
own status updates, without having to list all clients here). So typically
you will need to list your BBNET servers here.

The format of this option is a list of IP-adresses, optionally with a
network mask in the form of the number of bits. E.g. if you want to 
accept status-updates from the host 172.16.10.2, you would use
.br
    --status-senders=172.16.10.2
.br
whereas if you want to accept status updates from both 172.16.10.2 and
from all of the hosts on the 10.0.2.* network (a 24-bit IP network), you
would use
.br
    --status-senders=172.16.10.2,10.0.2.0/24

.IP "--maint-senders=IP[/MASK][,IP/MASK]"
Controls which hosts may send maintenance commands to hobbitd. Maintenance
commands are the "enable", "disable", "ack" and "notes" commands. Format
of this option is as for the --status-senders option. It is strongly
recommended that you use this to restrict access to these commands, so
that monitoring of a host cannot be disabled by a rogue user - e.g. to
hide a system compromise from the monitoring system.

.IP "--www-senders=IP[/MASK][,IP/MASK]"
Controls which hosts may send commands to retrieve the state of hobbitd. These
are the "hobbitdlog", "hobbitdboard" and "hobbitdlist" commands, which are used
by
.I bbgen(1)
and
.I bbcombotest(1)
to retrieve the state of the BB system so they can generate the BB webpages.

.IP "--admin-senders=IP[/MASK][,IP/MASK]"
Controls which hosts may send administrative commands to hobbitd. These
commands are the "hobbitddrop" and "hobbitdrename" commands. Access to these 
should be restricted, since they provide an un-authenticated means of completely
disabling monitoring of a host, and can be used to remove all traces of e.g.
a system compromise from the Big Brother monitor.

.IP "--debug"
Enable debugging output.

.IP "--dbghost=HOSTNAME"
For troubleshooting problems with a specific host, it may be useful to track
the exact communications from a single host. This option causes hobbitd to
dump all traffic from a single host to the file "/tmp/hobbitd.dbg".

.SH SIGNALS
.IP SIGHUP
Re-read the bb-hosts configuration file.

.IP SIGUSR1
Force an immediate dump of the checkpoint file.

.SH FILES
If ghost-handling is enabled via the "--ghosts" option, the $BBHOSTS
file is read to determine the names of all known hosts.

.SH "SEE ALSO"
bbgen-intro(7), bb-environ(5).

