.TH BBCOMBOTEST 1 "Version 3.1: 27 sep 2004" "bbgen toolkit"
.SH NAME
bbcombotest \- Big Brother combination test tool
.SH SYNOPSIS
.B "bbcombotest --help"
.br
.B "bbcombotest --version"
.br
.B "bbcombotest [--debug] [--quiet]"

.SH DESCRIPTION
.I bbcombotest
is a BB extension script that runs on the BBDISPLAY server. 
It combines the results of one or more of the normal
Big Brother test results into a combined test result, using
standard arithmetic og logical operators.

The resulting tests are sent to the Big Brother display server as any 
normal test - so all of the standard Big Brother functions (history,
statistics etc.) are available for the combined tests.

The tool was born from the need to monitor systems with built-in
redundancy and automatic failover - e.g. load-balanced web servers.
But other uses are possible.

bbcombotest must be installed on the BBDISPLAY server as an 
extension script, i.e. added to the $BBHOME/etc/bb-bbexttab file.

.SH OPTIONS
.IP "--quiet"
Normally, the test status sent by bbcombotest includes information
about the underlying test results used to determine the current
value of the combined test. "--quiet" eliminates this information
from the test status page.

.IP "--clean"
Big Brother normally does not permit the ampersand and pipe characters
in status messages, so the status message from bbcombotest may look a
bit odd. You can either permit all characters in status messages (by
recompiling the Big Brother daemon with the -DDONTCLEANSTRING option
enabled), or you can use this option with bbcombotest. It replaces
"||" with "OR", "&&" with "AND", "|" with "bOR" and "&" with "bAND".

.IP "--debug"
Provide debugging output for use in troubleshooting problems with
bbcombotest.

.IP "--no-update"
Dont send any status messages - instead, the result of the combotests
is simply dumped to stdout. Useful for debugging.


.SH FILES
.IP $BBHOME/etc/bbcombotest.cfg
Configuration file for bbcombotest, where the combined tests are defined
.IP $BBHOME/etc/bb-bbexttab
Big Brother extension-scripts file. bbcombotest must be added to this file
on the BBDISPLAY server so it will run as a Big Brother extension script.
.IP $BBLOGS/hostname.test
Big Brother status files, used to determine the current status of 
tests included in a combo-test.

.SH "SEE ALSO"
bbcombotest.cfg(5), bb-hosts(5), bb-environ(5)

