.TH CGIOPTIONS.CFG 5 "Version 4.2.3:  4 Feb 2009" "Xymon"
.SH NAME
cgioptions.cfg \- Command-line parameters for the Xymon CGI tools

.SH SYNOPSIS
.B $BBHOME/etc/cgioptions.cfg

.SH DESCRIPTION
.I cgioptions.cfg(1)
controls the command-line options passed to all of the Xymon CGI tools
through their respective shell-script wrappers. Typically the options
listed here are used for system-wide configuration of the CGI utilities,
e.g. to define where they read configuration files.

The exact set of command-line options available are described in the
man-page for each of the CGI utilities.

The file is "sourced" into the shell script wrapper, so assignments to
the CGI-specific variables must follow standard shell-script syntax.

.SH SETTINGS
.IP CGI_ACKINFO_OPTS
Options for the
.I hobbit-ackinfo.cgi(1)
utility.

.IP CGI_ACK_OPTS
Options for the
.I acknowledge.cgi(1)
utility.

.IP CGI_CSVINFO_OPTS
Options for the
.I csvinfo.cgi(1)
utility.

.IP CGI_DATEPAGE_OPTS
Options for the
.I datepage.cgi(1)
utility.

.IP CGI_ENADIS_OPTS
Options for the
.I hobbit-enadis.cgi(8)
utility.

.IP CGI_EVENTLOG_OPTS
Options for the
.I eventlog.cgi(1)
utility.

.IP CGI_FINDHOST_OPTS
Options for the
.I findhost.cgi(1)
utility.

.IP CGI_HIST_OPTS
Options for the
.I history.cgi(1)
utility.

.IP CGI_HOBBITCOLUMN_OPTS
Xymon-specific options for column documentation. This uses the
.I csvinfo.cgi(1)
utility with the \fBserver/etc/columndoc.cfg\fR configuration file.

.IP CGI_HOBBITCONFREPORT_OPTS
Options for the
.I hobbit-confreport.cgi(1)
utility.

.IP CGI_HOBBITGRAPH_OPTS
Options for the
.I hobbitgraph.cgi(1)
utility.

.IP CGI_HOSTGRAPHS_OPTS
Options for the
.I hobbit-hostgraphs.cgi(1)
utility.

.IP CGI_NKEDIT_OPTS
Options for the
.I hobbit-nkedit.cgi(1)
utility.

.IP CGI_NKVIEW_OPTS
Options for the
.I hobbit-nkview.cgi(1)
utility.

.IP CGI_REPLOG_OPTS
Options for the
.I reportlog.cgi(1)
utility.

.IP CGI_REP_OPTS
Options for the
.I report.cgi(1)
utility.

.IP CGI_SNAPSHOT_OPTS
Options for the
.I snapshot.cgi(1)
utility.

.IP CGI_SVCHIST_OPTS
Options for the
.I svcstatus.cgi(1)
utility when used to view historical logs. Note that the
"--historical" option must be included in this setting.

.IP CGI_SVC_OPTS
Options for the
.I svcstatus.cgi(1)
utility.

.SH "SEE ALSO"
xymon(7), the individual CGI utility man-pages.

