.TH HOBBIT-NKVIEW.CGI 1 "Version 4.2.3:  4 Feb 2009" "Xymon"
.SH NAME
hobbit-nkview.cgi \- Xymon Critical Systems view CGI
.SH SYNOPSIS
.B "hobbit-nkview.cgi"

.SH DESCRIPTION
\fBhobbit-nkview.cgi\fR is invoked as a CGI script via the 
hobbit-nkview.sh CGI wrapper.

hobbit-nkview.cgi matches the current critical statuses against the
.I critical.cfg(5)
file, and generates the "Critical Systems" view. 

.SH RELATION TO BBNK PAGE
This view is a replacement for the statically generated "bbnk" page 
provided in versions of Xymon prior to version 4.2. Although the 
"bbnk" pages are supported throughout Xymon 4.x, it is recommended 
that You switch to the newer Critical Systems view provided by this CGI.

.SH OPTIONS
.IP "--nkacklevel=NUMBER"
Sets the acknowledgment level for acknowledgments sent via the
.I hobbit-ackinfo.cgi(1)
page. Note that this may be overridden by the configuration of the
hobbit-ackinfo.cgi utility.

.IP "--env=FILENAME"
Loads the environment defined in FILENAME before executing the CGI script.

.IP "--area=NAME"
Load environment variables for a specific area. NB: if used,
this option must appear before any --env=FILENAME option.

.IP "--debug"
Enables debugging output.

.IP "--nkconfig=FILENAME"
Use FILENAME as the configuration file for the Critical 
Systems information. The default is to load this from
$BBHOME/etc/critical.cfg

.SH "ENVIRONMENT VARIABLES"
.IP BBHOME
Used to locate the template files for the generated web pages.

.IP QUERY_STRING
Contains the parameters for the CGI script.

.SH "SEE ALSO"
hobbit-ackinfo.cgi(1), xymon(7)

