.TH BB-ENVIRON 5 "Version 2.6: 24 Jul 2003" "bbgen toolkit"
.SH NAME
bb-environ \- bbgen specific environment variables

.SH DESCRIPTION
The bbgen toolkit uses some environment variables beside the
normal set of variables defined by the Big Brother configuration
files. This manpage documents these extra environment variables.

For a description of the standard Big Brother environment
variables, please see the Big Brother documentation.

You will normally need to define the bbgen environment variables in
your $BBHOME/etc/bbsys.local file, so that they are available
to the bbgen toolkit programs when they execute as part of
the Big Brother programs.

.SH ENVIRONMENT VARIABLES

.IP BBGEN
Defines the location of the
.I bbgen(1)
program. 
.br
Default: $BBHOME/bin/bbgen

.IP BBGHOSTS
The bbgen patch for the Big Brother daemon bbd introduces a new
way of handling status reports from hosts that are not in the
.I bb-hosts(5)
file. What happens is controlled by setting BBHOSTS to 0, 1 or 2.
.br
By default, these status messages are just stored as if
the hosts were known to the Big Brother system - this behaviour
is what you get if BBGHOSTS is undefined, or set to 0.
.br
BBHOSTS=1 causes the status report to be silently discarded.
.br
BBHOSTS=2 also discards the status report, but logs a message
to BBOUT with the hostname that was ignored.

.IP BBMAXMSGSPERCOMBO
The maximum number of status messages to combine into one
combo message. You may need to lower this number of your
BBDISPLAY server has trouble keeping up with the incoming
status messages from bbtest-net.
.br
Default: 0 (unlimited)

.IP BBSLEEPBETWEENMSGS
Length of a pause introduced between each successive transmission
of a combo-message by bbtest-net. You may have to increase this
value to give your BBDISPLAY server time to process one combo
message before the next one arrives. This number defines how
many milliseconds to wait between the messages.
.br
Default: 0 (send messages as quickly as possible).

.IP BBHTACCESS
Defines the contents of the top-level .htaccess file created by bbgen
when run with the --htaccess option. This .htaccess file is
created in the toplevel directory where the bb.html and bb2.html
files are stored.
.br
Default: none

.IP BBPAGEHTACCESS
Defines the contents of the page-level .htaccess file created by bbgen
when run with the --htaccess option. This .htaccess file is
created in the first level directory corresponding the the location
of the "page" webpages. This setting may include a "%s" tag, which will
automatically be expanded to the name of the current page.
.br
Default: none

.IP BBSUBPAGEHTACCESS
Defines the contents of the subpage-level .htaccess file created by bbgen
when run with the --htaccess option. This .htaccess file is
created below the first level directory corresponding the the location
of the "subpage" and "subparent" webpages. This setting may include two "%s" 
tags, which will automatically be expanded to the name of the current page
and subpage, respectively.
.br
Default: none

.IP BBHELPSKIN
The URL prefix used for accessing the Big Brother on-line helpfiles.
When generating reports and snapshots, it may be necessary to set
this to the standard location of the help-files in order for the
help-links to work.

.IP BBNOTESSKIN
The URL prefix used for accessing the Big Brother on-line notes.
When generating reports and snapshots, it may be necessary to set
this to the standard location of the notes-files in order for the
notes-links to work.

.IP BBGENREPOPTS
Default bbgen options used by reports. This will typically include
such options as "--subpagecolumns", "--larrd", "--info" and also
"--ignorecolumns" if you wish to exclude certain tests from reports
by default.

.IP BBGENSNAPOPTS
Default bbgen options used by snapshots. This should be identical to
the options you normally used when building Big Brother webpages.

.IP BBSNAP
The location of files generated by the
.I bb-snapshot.cgi(1)
utility.

.IP BBSNAPURL
The URL prefix used to access files generated by the
.I bb-snapshot.cgi(1)
utility.

.IP FPING
Defines the location of the
.I fping(1)
program. 
.br
Default: None (uses PATH setting to find program).

.IP NSLOOKUP
Defines the location of the
.I nslookup(1)
program. 
.br
Default: None (uses PATH setting to find program).

.IP DIG
Defines the location of the
.I dig(1)
program. 
.br
Default: None (uses PATH setting to find program).

.IP NTPDATE
Defines the location of the
.I ntpdate(1)
program. 
.br
Default: None (uses PATH setting to find program).

.SH FILES
.I $BBHOME/etc/bbsys.local

