#!/bin/bash

hg init a
cd a
echo a > a
hg ci -A -m 'First commit'

echo a >> a

#$ name: tip

#$ name: commit

hg status
echo b > b
hg commit -m 'Add file b'

#$ name: status

hg status
hg tip

#$ name: rollback

hg rollback
hg tip
hg status

#$ name: add

hg add b
hg commit -m 'Add file b, this time for real'

#$ name: twice

hg rollback
hg rollback
