.TH XYMONCLIENT.CFG 5 "Version 4.3.27: 24 Mar 2016" "Xymon"
.SH NAME
xymonclient.cfg \- Xymon client environment variables

.SH DESCRIPTION
Xymon programs use multiple environment variables beside the
normal set of variables.  For the Xymon client, the environment 
definitions are stored in the ~xymon/client/etc/xymonclient.cfg file. 
Each line in this file is of the form \fBNAME=VALUE\fR and defines
one environment variable NAME with the value VALUE.

.SH SETTINGS
.IP XYMSRV
The IP-address used to contact the Xymon server. Default:
Chosen when the Xymon client was compiled.

.IP XYMSERVERS
List of IP-addresses of Xymon servers. Data will be sent to
all of the servers listed here. This setting is only used if 
XYMSRV=0.0.0.0.

.IP XYMONDPORT
The port number for used to contact the Xymon server.
Default: 1984.

.IP XYMONHOME
The Xymon client top-level directory. Default: The
$XYMONCLIENTHOME setting inherited from the "runclient.sh"
script which starts the Xymon client.

.IP XYMONCLIENTLOGS
The directory for the Xymon clients' own log files. Default:
$XYMONHOME/logs

.IP XYMONTMP
Directory used for temporary files. Default: $XYMONHOME/tmp/

.IP XYMON
Full path to the 
.I xymon(1)
client program. Default: $XYMONHOME/bin/xymon.

.IP Commands
Many extension scripts expect a series of environment variables to
point at various system utilities. These are included in the file
when the client is built.

.SH INHERITED SETTINGS
Some environment variables are inherited from the "runclient.sh"
script which launches the Xymon client:

.IP MACHINEDOTS
The hostname of the local system. Default: Taken from "uname \-n".

.IP MACHINE
The hostname of the local system, with dots replaced by commas.
For compatibility with Big Brother extension scripts.

.IP SERVEROSTYPE
The operating system of the local system, in lowercase. Default:
taken from "uname \-s".

.IP XYMONCLIENTHOME
The top-level directory for the Xymon client. Default: The location
of the "runclient.sh" script.

.SH "SEE ALSO"
xymon(7)

