.TH BBRETEST-NET.SH 1 "Version 4.2:  7 Aug 2006" "Hobbit Monitor"
.SH NAME
bbretest-net.sh \- Hobbit network re-test tool
.SH SYNOPSIS
.B "bbretest-net.sh"

.SH DESCRIPTION
\fBbbretest-net.sh\fR
is an extension script for Hobbit that runs on the network
test server.  It picks up the failing network tests executed by the 
.I bbtest-net(1)
program, and repeats these tests with a faster test cycle
than the normal bbtest-net schedule. This means that when
the server recovers and the network service becomes available
again, this is detected quicker resulting in less reported
downtime.

Only tests whose first failure occurred within 30 minutes
are included in the tests that are run by bbretest-net.sh.
The 30 minute limit is there to avoid hosts that are down for
longer periods of time to bog down bbretest-net.sh.  You can change 
this limit with the "--frequenttestlimit=SECONDS" when you run
bbtest-net.


.SH INSTALLATION
This script runs by default from your
.I hobbitlaunch.cfg(5)
file.


.SH FILES
.IP $BBTMP/TESTNAME.LOCATION.status
Temporary status file managed by bbtest-net with status of tests that have currently failed.
.IP $BBTMP/frequenttests.LOCATION
Temporary file managed by bbtest-net with the hostnames that bbretest-net.sh should test.

.SH "SEE ALSO"
bbtest-net(1), hobbit(7), hobbitlaunch.cfg(5)

