.TH BBTEST-NET 1 "Version 2.8: 16 Aug 2003" "bbgen toolkit"
.SH NAME
bbtest-net \- Big Brother network test engine
.SH SYNOPSIS
.B "bbtest-net -?"
.br
.B "bbtest-net --help"
.br
.B "bbtest-net --version"
.br
.B "bbtest-net [options]"
.br
(See the OPTIONS section for a description of the available commandline options).

.SH DESCRIPTION
.I bbtest-net
is a drop-in replacement for the bb-network.sh network test script 
provided by Big Brother. bbtest-net implements all of the network
tests normally performed by the bb-network.sh script, with built-in
support for a large number of test types that would normally
require additional add-on extensions.

Also, bbtest-net executes tests much faster than the standard
bb-network.sh script.

bbtest-net does all of the normal tests of TCP-based network
services (telnet, ftp, ssh, smtp, pop, imap ....) - i.e. 
all of the services listed as BBNETSVCS in bbdef.sh. For
these tests, a completely new and very speedy service-
checker has been implemented.

bbtest-net has built-in support for testing SSL-enabled
protocols, e.g. imaps, pop3s, nntps, telnets, if SSL-support
was enabled when configuring bbgen. To fully enable these,
you must make sure that these protocols are defined in
your /etc/services file, and they must be added to the
BBNETSVCS setting in $BBHOME/etc/bbdef.sh.

In addition, it implements the "dns" and "dig" tests for
testing DNS servers. This is done in the same way as 
bb-network.sh does it. 

bbtest-net also implements a check for NTP servers - this test 
is called "ntp". If you want to use it, you must define the
NTPDATE environment variable to point at the location of your
.I ntpdate(1)
program.

Note: Unlike the standard Big Brother network test tool,
bbtest-net performs the connectivity test (ping) based on the
hostname, unless the host is tagged with "testip" or the 
"--dns=ip" option is used. So the target of the connectivity
test can be determined by your /etc/hosts file or DNS.


.SH GENERAL OPTIONS

.IP "--help or -?"
Provide a summary of available commandline options.

.IP "--version"
Prints the version number of bbtest-net

.IP --dns=[ip|only]
Determines how bbtest-net finds the IP adresses of the hosts to test. 
By default, bbtest-net does a DNS lookup of the hostname 
to determine the IP address, unless the host has the "testip" 
tag, or the DNS lookup fails.
.br
With "--dns=only" bbtest-net will ONLY do the DNS lookup;
it it fails, then all services on that host will be 
reported as being down.
.br
With "--dns=ip" bbtest-net will never do a DNS lookup;
it will use the IP adresse specified in bb-hosts for
the tests. Thus, this setting is equivalent to having
the "testip" tag on all hosts. Note that http tests
will ignore this setting and still perform a DNS
lookup for the hostname given in the URL; see the
"bbtest-net tags for HTTP tests" section in
.I bb-hosts(5)

.IP --debug
Dumps a bunch of status about the tests as they
progress to stdout.

.IP --no-update
Don't send any status updates to the BBDISPLAY server. Instead,
all messages are dumped to stdout.

.IP --report[=COLUMNNAME]
With this option, bbtest-net will send a status message with details 
of how many hosts were processed, how many tests were generated, 
any errors that occurred during the run, and some timing statistics. 
The default columnname is "bbtest".

.IP --timing
Causes bbtest-net to collect information about
the time spent in different parts of the program.
The information is printed on stdout just before
the program ends. Note that this information is also
included in the status report sent with the "--report"
option.


.SH OPTIONS FOR THE PING TEST
.IP --ping[=conn-column-name]
Enables bbtest-net's ping test, and optionally specifies
the column name used to report the results of the ping test.
.br
Note that bbtest-net uses the
.I fping(1) 
tool to implement ping checks, so this must be installed.
.br
If not specifed, bbtest-net uses the CONNTEST environment
variable to determine if it should perform the ping test
or not. So if you prefer to use another tool to implement 
ping checks, either set the CONNTEST environment variable 
to false, or run bbtest-net with the "--noping".
.br
bbtest-net has support for the "badconn" tag that 
fping.sh uses, see
.I bb-hosts(5)

.IP --noping
Disable the connectivity test.

.SH OPTIONS FOR THE SIMPLE TCP SERVICES
.IP --checkresponse
When testing FTP, SSH, SMTP, POP-2, POP-3, IMAP, NNTP and rsync
services, bbtest-net will look for a valid service-specific
"OK" response. If another reponse is seen, this will cause
the test to report a warning (yellow) status.

.IP --concurrency=N 
Determines the number of network tests that
run in parallel. Default is operating system dependent,
but will usually be 256. If bbtest-net begins to complain 
about not being able to get a "socket", try running
bbtest-net with a lower value like 50 or 100.

.IP --timeout=N
Determines the timeout (in seconds) for each
service that is tested. For TCP tests (those from BBNETSVCS),
if the connection to the service does not succeed within N 
seconds, the service is reported as being down. For HTTP
tests, this is the absolute limit for the entire request
to the webserver (the time needed to connect to the server,
plus the time it takes the server to respond to the request).


.SH OPTIONS FOR HTTP (WEB) TESTS
.IP --conntimeout=N
Determines the connection timeout for a HTTP test. This only 
applies to HTTP tests, and sets a limit for the time it takes 
to just initiate the connection to the webserver. It must be 
less than the "--timeout" setting.

.IP --content=CONTENTTESTNAME 
Determines the name of the column BB displays for content checks. 
The default is "content".  If you have used the "cont.sh" or "cont2.sh" 
scripts earlier, you may want to use "--content=cont" to report content
checks using the same test name as these scripts do.

.IP --log=LOGFILENAME
Enables logging of all traffic from HTTP/HTTPS servers. Mostly useful for 
debugging.


.SH SSL CERTIFICATE CHECKS
When bbtest-net tests services that use SSL- or TLS-based protocols,
it will check that the server certificate has not expired. This check
happens automatically for https (secure web), pop3s, imaps, nntps
and all other SSL-enabled services (except ldap, see LDAP TESTS 
below).

All certificates found for a host are reported in one status message.

.IP --ssl=SSLCERTTESTNAME
determines the name of the column BB displays for the SSL certificate checks.
The default is "sslcert".
.IP --no-ssl
Disables reporting of the SSL certificate check.

.IP --sslwarn=N
.IP --sslalarm=N
Determines the number of days before an SSL certificate
expires, where bbtest-net will generate a warning or
alarm status for the SSL certificate column.

.SH LDAP TESTS
ldap testing can be done in two ways. If you just put an "ldap" or
"ldaps" tag in bb-hosts, a simple test is performed that just verifies
that it is possible to establish a connection to the port running 
the ldap service (389 for ldap, 636 for ldaps).

Instead you can put an LDAP URI in bb-hosts. This will cause 
bbtest-net to initiate a full-blown LDAP session with the server,
and do an LDAP search for the objects defined by the URI. This
requires that bbtest-net was built with LDAP support, and relies
on an existing LDAP library to be installed.  It has been tested 
with OpenLDAP 2.0.26 (from Red Hat 9) and 2.1.22.  The Solaris 8 
system ldap library has also been confirmed to work for un-encrypted 
(plain ldap) access.

The format of LDAP URI's is defined in RFC 2255. LDAP URLs look like this:
.nf

  \fBldap://\fP\fIhostport\fP\fB/\fP\fIdn\fP[\fB?\fP\fIattrs\fP[\fB?\fP\fIscope\fP[\fB?\fP\fIfilter\fP[\fB?\fP\fIexts\fP]]]]

where:
  \fIhostport\fP is a host name with an optional ":portnumber"
  \fIdn\fP is the search base
  \fIattrs\fP is a comma separated list of attributes to request
  \fIscope\fP is one of these three strings:
    base one sub (default=base)
  \fIfilter\fP is filter
  \fIexts\fP are recognized set of LDAP and/or API extensions.

Example:
  ldap://ldap.example.net/dc=example,dc=net?cn,sn?sub?(cn=*)
.fi
.sp
All "bind" operations to LDAP servers use simple authentication.
Kerberos and SASL are not supported. If your LDAP server requires 
a username/password, use the "ldaplogin" tag to specify this, cf. 
.I bb-hosts(5) 
If no username/password information is provided, an anonymous
bind will be attempted. 

SSL support requires both a client library and an LDAP server that support LDAPv3; 
it uses the LDAP "STARTTLS" protocol request after establishing a connection to 
the standard (non-encrypted) LDAP port (usually port 389). It has only been
tested with OpenSSL 2.x, and probably will not work with any other LDAP library.

The older LDAPv2 experimental method of tunnelling normal LDAP traffic through an 
SSL connection - ldaps, running on port 636 - is not supported, unless someone 
can explain how to get the OpenLDAP library to support it. This method was never
formally described in an RFC, and implementations of it are non-standard.

For a discussion of the various ways of running encrypted ldap, see
http://www.openldap.org/lists/openldap-software/200305/msg00079.html
http://www.openldap.org/lists/openldap-software/200305/msg00084.html
http://www.openldap.org/lists/openldap-software/200201/msg00042.html
http://www.openldap.org/lists/openldap-software/200206/msg00387.html

When testing LDAP URI's, all of the communications are handled 
by the ldap library. Therefore, it is not possible to obtain the 
SSL certificate used by the LDAP server, and it will not show up 
in the "sslcert" column.


.SH USING MULTIPLE BBNET SYSTEMS
If you have more than one BBNET system - e.g. if your network
is separated by firewalls - then is is problematic to maintain
multiple bb-hosts files for each of the BBNET systems.
bbtest-net supports the NET:location tag in
.I bb-hosts(5)
to distinguish 
between hosts that should be tested from different network
locations. If you set the environment variable BBLOCATION
e.g. to "dmz" before running bbtest-net, then it will only
test hosts that have a "NET:dmz" tag in bb-hosts. This allows
you to keep all of your hosts in the same bb-hosts file, but
test different sets of hosts by different BBNET systems.


.SH BBTEST-NET INTERNALS
bbtest-net first scans the bb-hosts file, and collects information
about the TCP service tests that need to be tested. It picks out only
the tests that are listed in the BBNETSVCS setting, plus the "dns",
"dig" and "ntp" tests - those tests that bb-network.sh would normally 
use the "bbnet" tool to test.

All of the TCP-based service checks are then handled by a connection
tester written specifically for this purpose. It uses only standard
Unix-style network programming, but relies on the Unix "select(2)" 
system-call to handle many simultaneous connections happening in 
parallel. Exactly how many parallel connections are being used 
depends on your operating system - the default is FD_SETSIZE/4,
which amounts to 256 on many Unix systems.

You can choose the number of concurrent connections with the
"--concurrency=N" option to bbtest-net.

Connection attempts timeout after 10 seconds - this can be
changed with the "--timeout=N" option. This value is in seconds.

Both of these settings play a part in deciding how long the testing
takes. A conservative estimate for doing N TCP tests is:

   (1 + (N / concurrency)) * timeout

In real life it will probably be less, as the above formula is for
every test to require a timeout. Since the most normal use of BB
is to check for services that are active, you should have a lot
less timeouts.

The "http" and "content" checks use the CURL library to perform
all checks.

The "dns", "dig" and "ntp" checks rely on external programs to 
do each test. Thus, they perform only marginally better than the
standard bb-network.sh script. 

.SH BBTEST-NET PERFORMANCE
The speed of bbtest-net depends on a number of circumstances,
including your mix of services to test, network bandwidth
etc. However, it is safe to say that it is magnitudes faster than 
the stock Big Brother tools.

In addition to being fast, it is also much lighter on your system
load than the normal Big Brother tools. By using a single program
for most of the work, it significantly reduces the load on your
BBNET host - I've seen load averages drop by a factor 10 when
moving from standard BB test tools to bbtest-net.

If you really want some numbers:
.IP
bbtest-net checks 300 web sites in 15 seconds on a slow Sun Ultra5.
Half of those are SSL sites.
.IP
bbtest-net checks 1000 tcp services in 20 seconds on a recent
FreeBSD 4.6.2 system

.SH ENVIRONMENT VARIABLES
.IP BBLOCATION
Defines the network segment where bbtest-net is currently running.
This is used to filter out only the entries in the
.I bb-hosts(5)
file that have a matching "NET:LOCATION" tag, and execute the
tests for only those hosts.

.IP BBMAXMSGSPERCOMBO 
Defines the maximum number of status messages that can be sent in 
one combo message. Default is 0 - no limit.
.br
In practice, the maximum size of a single BB message
sets a limit - the default value for the maximum message
size is 8 KB, but that will easily accomodate 50 status
messages per transmission. So if you want to experiment
with this setting, I suggest starting with a value of 10.

.IP BBSLEEPBETWEENMSGS
Defines a a delay (in microseconds) after each 
message is transmitted to the BBDISPLAY server. The default 
is 0, i.e.  send the messages as fast as possible.
This gives your BBDISPLAY server some time to process the
message before the next message comes in. Depending on
the speed of your BBDISPLAY server, it may be necessary
to set this value to half a second or even 1 or 2 seconds.
Note that the value is specified in MICROseconds, so to
define a delay of half a second, this must be set to
the value "500000"; a delay of 1 second is achieved by
setting this to "1000000" (one million).

.IP FPING
Location of the fping(8) utility. Used by bbtest-net for connectivity
(ping) testing.

.IP NTPDATE
Location of the ntpdate(1) utility. Used by bbtest-net when checking 
the "ntp" service.

.IP NSLOOKUP
Location of the nslookup(1) utility. Used by bbtest-net when checking 
the "dns" service.

.IP DIG
Location of the dig(1) utility. Used by bbtest-net when checking 
the "dig" service.

.SH FILES
.IP $HOME/.netrc - authentication data for password-protected webs
bbtest-net uses the CURL library, which supports the use of a
~/.netrc file. If you have password-protected sites, you can put 
the username and password into the ".netrc" file in the bb users' 
home-directory. See 
.I curl(1)
for details - a sample entry would look like this
.br
   machine www.acme.com login fred password Wilma1
.br
Note that the machine-name must be the name you use in the
http://machinename/ URL setting - it need not be the one you
use for the system-name in Big Brother.

This works for web-sites that use the "Basic" authentication
scheme in HTTP.
.sp
.IP $BBTMP/*.status - test status summary
Each time bbtest-net runs, if any tests fail (i.e. they result
in a red status) then they will be listed in a file name
TESTNAME.[LOCATION].status. The LOCATION part may be null. This
file is used to determine how long the failure has lasted, which
in turn decides if this test should be included in the tests done by
.I bbretest-net.sh(1)
.br
It is also used internally by bbtest-net when determining the
color for tests that use the "badconn" or "badTESTNAME" tags.
.sp
.IP $BBTMP/frequenttests.[LOCATION]
This file contains the hostnames of those hosts that should be
retested by the
.I bbretest-net.sh(1)
test tool. It is updated only by bbtest-net during the normal
runs, and read by bbretest-net.sh.

.SH "SEE ALSO"
bb-hosts(5), bb-environ(5), curl(1), fping(1), nslookup(1), dig(1),
ntpdate(1)

