#!/bin/bash

hg init a
cd a
mkdir -p examples src/watcher
touch COPYING MANIFEST.in README setup.py
touch examples/performant.py examples/simple.py
touch src/main.py src/watcher/_watcher.c src/watcher/watcher.py src/xyzzy.txt

#$ name: files

hg add COPYING README examples/simple.py

#$ name: dirs

hg status src

#$ name: wdir-subdir

cd src
hg add -n
hg add -n .

#$ name: wdir-relname

hg status
hg status `hg root`

#$ name: glob.star

hg add 'glob:*.py'

#$ name: glob.starstar

cd ..
hg status 'glob:**.py'

#$ name: glob.star-starstar

hg status 'glob:*.py'
hg status 'glob:**.py'

#$ name: glob.question

hg status 'glob:**.?'

#$ name: glob.range

hg status 'glob:**[nr-t]'

#$ name: glob.group

hg status 'glob:*.{in,py}'

#$ name: filter.include

hg status -I '*.in'

#$ name: filter.exclude

hg status -X '**.py' src
