#!/bin/bash

hg init a
cd a
echo hello > myfile
hg commit -A -m 'Initial commit'

#$ name: branches

hg tip
hg branches

#$ name: branch

hg branch

#$ name: create

hg branch foo
hg branch

#$ name: status

hg status
hg tip

#$ name: commit

echo 'hello again' >> myfile
hg commit -m 'Second commit'
hg tip

#$ name: rebranch

hg branch
hg branch bar
echo new file > newfile
hg commit -A -m 'Third commit'
hg tip

#$ name: parents

hg parents
hg branches

#$ name: update-switchy

hg update foo
hg parents
hg update bar
hg parents

#$ name: update-nothing

hg update foo
hg update

#$ name: foo-commit

echo something > somefile
hg commit -A -m 'New file'
hg heads

#$ name: update-bar

hg update bar
hg update -C bar

#$ name: merge

hg branch
hg merge
hg commit -m 'Merge'
hg tip
