# Toplevel Makefile for Xymon
BUILDTOPDIR=`pwd`
CLIENTONLY = yes
LOCALCLIENT = no

# configure settings for Xymon
#
# Toplevel dir
BBTOPDIR = /home/xymon
# Server home dir for etc/, www/
BBHOME = /home/xymon/client

# Xymon settings follows
#
# Username running Xymon
BBUSER = xymon
# Xymon server IP-address
BBHOSTIP = 127.0.0.1
# Large File Support settings
LFSDEF = -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
LIBRTDEF = -lrt

include build/Makefile.Linux


#
# Add local CFLAGS etc. settings here

include build/Makefile.rules

