.TH EVENTLOG.CGI 1 "Version 4.3.19: 30 Mar 2015" "Xymon"
.SH NAME
eventlog.cgi \- CGI program to report the Xymon eventlog
.SH SYNOPSIS
.B "eventlog.cgi"

.SH DESCRIPTION
\fBeventlog.cgi\fR
is invoked as a CGI script via the eventlog.sh CGI wrapper.
Based on the parameters it receives, it generates the
Xymon event log for a period. This log shows all status
changes that have occurred for all hosts and services.

eventlog.cgi is passed a QUERY_STRING environment variable 
with the following parameters:

   MAXTIME (maximum minutes to go back in the log)
   MAXCOUNT (maximum number of events to report)

.SH OPTIONS
.IP "--env=FILENAME"
Loads the environment defined in FILENAME before executing the CGI script.

.SH "SEE ALSO"
hosts.cfg(5), xymonserver.cfg(5)

