.TH XYMONNET-AGAIN.SH 1 "Version 4.3.17: 23 Feb 2014" "Xymon"
.SH NAME
xymonnet-again.sh \- Xymon network re-test tool
.SH SYNOPSIS
.B "xymonnet-again.sh"

.SH DESCRIPTION
\fBxymonnet-again.sh\fR
is an extension script for Xymon that runs on the network
test server.  It picks up the failing network tests executed by the 
.I xymonnet(1)
program, and repeats these tests with a faster test cycle
than the normal xymonnet schedule. This means that when
the server recovers and the network service becomes available
again, this is detected quicker resulting in less reported
downtime.

Only tests whose first failure occurred within 30 minutes
are included in the tests that are run by xymonnet-again.sh.
The 30 minute limit is there to avoid hosts that are down for
longer periods of time to bog down xymonnet-again.sh.  You can change 
this limit with the "--frequenttestlimit=SECONDS" when you run
xyxmonnet.


.SH INSTALLATION
This script runs by default from your
.I tasks.cfg(5)
file.


.SH FILES
.IP $XYMONTMP/TESTNAME.LOCATION.status
Temporary status file managed by xyxmonnet with status of tests that have currently failed.
.IP $XYMONTMP/frequenttests.LOCATION
Temporary file managed by xymonnet with the hostnames that xymonnet-again.sh should test.

.SH "SEE ALSO"
xymonnet(1), xymon(7), tasks.cfg(5)

