.TH BB 1 "Version 4.0.2: 10 apr 2005" "Hobbit Monitor"
.SH NAME
bb \- Hobbit client communication program
.SH SYNOPSIS
.B "bb [options] RECIPIENT message"

.SH DESCRIPTION
.I bb(1)
is the client program used to communicate with a
Hobbit server. It is frequently used by Hobbit
client systems to send in status messages and pager
alerts on local tests.

In Hobbit, the bb program is also used for administrative
purposes, e.g. to rename or delete hosts, or to disable
hosts that are down for longer periods of time.

.SH OPTIONS AND PARAMETERS
.IP "--debug"
Enable debugging. This prints out details about how the
connection to the BBDISPLAY server is being established.

.IP "--proxy=http://PROXYSERVER:PROXYPORT/"
When sending the status messages via HTTP, use this server
as an HTTP proxy instead of connecting directly to the BBDISPLAY
server.

.IP "--timeout=N"
Specifies the timeout for connecting to the Hobbit server, in
seconds. The default is 5 seconds.

.IP "RECIPIENT"
The \fBRECIPIENT\fR parameter defines which server receives
the message. If RECIPIENT is given as "0.0.0.0", then the
message is sent to all of the servers listed in the BBDISPLAYS
or BBPAGERS environment variable (for "status" and "page" messages,
respectively). 

Usually, a client will use "$BBDISP" for the \fBRECIPIENT\fR 
parameter, as this is defined by the client scripts
to automatically contain the correct value from the
.I bb-hosts(5)
file.

The \fBRECIPIENT\fR parameter may be a URL for a webserver
that has the bbmessage.cgi or similar script installed. This
tunnels the Hobbit messages to the BBDISPLAY server 
using standard HTTP protocol. The 
.I bbmessage.cgi(1)
CGI script provided as part of the bbgen toolkit must be
installed on the webserver for the HTTP transport to work.
.br

.IP MESSAGE
The \fBmessage\fR parameter is the message to be sent across
to the Hobbit server. Messages must be enclosed in quotes,
but by doing so they can span multiple lines. The maximum size
of a message is defined by the MAXMSG compile-time setting
and defaults to 32 KB.

.SH HOBBIT MESSAGE SYNTAX

This section lists the most commonly used messages in the Hobbit
protocol.

Each message must begin with one of the Hobbit commands. Where
a HOSTNAME is specified, it must have any dots in the hostname changed
to commas if the Hobbit FQDN setting is enabled (which is the default).
So e.g. the host "www.foo.com" would report as "www,foo,com".

.IP "status HOSTNAME.TESTNAME COLOR <additional text>"
This sends in a status message for a single test (column) on a single host.
TESTNAME is the name of the column where this test will show up; any
name is valid except that using dots in the testname will not work.
COLOR must be one of the valid colors: "green", "yellow", "red" or "clear".
The colors "blue" and "purple" - although valid colors - should not be sent in a
status-message, as these are handled specially by the Hobbit server.
.br
The "additional text" normally includes a local timestamp and a summary
of the test result on the first line. Any lines following the first one
are free-form, and can include any information that may be useful to
diagnose the problem being reported.

.IP "notify HOSTNAME.TESTNAME <message text>"
Hobbit only, not supported by BB. This triggers an informational 
message to be sent to those who receive alerts for this HOSTNAME+TESTNAME
combination, according to the rules defined in
.I hobbit-alerts.cfg(5)
This is used by the Hobbit \fBmaint.pl\fR script to notify people
about hosts being disabled or enabled, but can also serve as a 
general way of notifying server administrators.

.IP "data HOSTNAME.DATANAME<newline><additional text>"
The "data" message allows tools to send data about a host, without
it appearing as a column on the Hobbit webpages. This
is used e.g. to report statistics about a host, e.g. vmstat data which
does not in itself represent something that has a red, yellow or
green identity. It is used by LARRD bottom-feeder modules, among
others. In Hobbit, data messages are by default processed only by the
.I hobbitd_larrd(8)
module. If you want to handle data-messages by an external application,
you may want to enable the 
.I hobbitd_filestore(8)
module for data-messages, to store data-messages in a format compatible
with how the Big Brother daemon does.

.IP "disable HOSTNAME.TESTNAME DURATION <additional text>"
Disables a specific test for DURATION minutes. This will cause the
status of this test to be listed as "blue" on the BBDISPLAY server,
and no alerts for this host/test will be generated. If DURATION is
given as a number followed by s/m/h/d, it is interpreted as being
in seconds/minutes/hours/days respectively.

.IP "enable HOSTNAME.TESTNAME"
Re-enables a test that had been disabled.

.IP "query HOSTNAME.TESTNAME"
Query the BBDISPLAY server for the latest status reported for this
particular test. If the host/test status is known, the response is
the first line of the status report - the current color will be the
first word on the line. Additional lines of text that might be 
present on the status-message cannot be retrieved.
.br
This allows any Hobbit client to determine the status of a particular
test, whether it is one pertaining to the host where the client
is running, some other host, or perhaps the result of a combined
test from multiple hosts managed by
.I bbcombotest(1)
This will typically be useful to Hobbit client extension scripts, that
need to determine the status of other hosts e.g. to decide if an
automatic recovery action should be initiated.

.IP "config FILENAME"
Retrieve one of the Hobbit configuration files from the
server. This command allows a client to pull files from the
$BBHOME/etc/ directory on the server, allowing for semi-automatic
updates of the client configuration. Since the configuration files 
are designed to have a common file for the configuration of all hosts 
in the system - and this is in fact the recommended way of configuring 
your clients - this makes it easier to keep the configuration 
files synchronized.

.IP "drop HOSTNAME"
Removes all data stored about the host HOSTNAME. It is assumed that you
have already deleted the host from the bb-hosts configuration file.

.IP "drop HOSTNAME TESTNAME"
Remove data about a single test (column).

.IP "rename OLDHOSTNAME NEWHOSTNAME"
Rename all data for a host that changes its name. You should do this
before changing the hostname in the bb-hosts configuration file.

.IP "rename HOSTNAME OLDTESTNAME NEWTESTNAME"
Rename data about a single test (column).

.IP "hobbitdlog HOSTNAME.TESTNAME"
Retrieve the Hobbit status-log for a single test. The first line of the
response contain a series of fields separated by a pipe-sign:
.sp
.BR hostname
The name of the host
.sp
.BR testname
The name of the test
.sp
.BR color
Status color (green, yellow, red, blue, clear, purple)
.sp
.BR testflags
For network tests, the flags indicating details about the test (used by bbgen).
.sp
.BR lastchange
Unix timestamp when the status color last changed.
.sp
.BR logtime
Unix timestamp when the log message was received.
.sp
.BR validtime
Unix timestamp when the log message is no longer valid (it goes purple at this time).
.sp
.BR acktime
-1, or Unix timestamp when an active acknowledgement expires.
.sp
.BR disabletime
-1, or Unix timestamp when the status is no longer disabled.
.sp
.BR sender
IP-address where the status was received from.
.sp
.BR cookie
-1, or the cookie value used to acknowledge an alert.
.sp
.BR ackmsg
Empty, or the acknowledgment message sent when the status was acknowledged.
Newline, pipe-signs and backslashes are escaped by with a backslash in C-style.
.sp
.BR dismsg
Empty, or the message sent when the status was disabled.
Newline, pipe-signs and backslashes are escaped by with a backslash in C-style.
.sp
After the first line comes the full status log in plain text format.

.IP "hobbitdxlog HOSTNAME.TESTNAME"
Retrieves an XML-string with the status log as for the 
"hobbitdlog" command.

.IP "hobbitdboard"
Retrieves a summary of the status of all known tests available to
the Hobbit daemon. This returns one line for each HOSTNAME.TESTNAME
combination that has reported to Hobbit, with the following information
for each status (fields are separated by pipe-signs):
.sp
.BR hostname
The name of the host
.sp
.BR testname
The name of the test
.sp
.BR color
Status color (green, yellow, red, blue, clear, purple)
.sp
.BR testflags
For network tests, the flags indicating details about the test (used by bbgen).
.sp
.BR lastchange
Unix timestamp when the status color last changed.
.sp
.BR logtime
Unix timestamp when the log message was received.
.sp
.BR validtime
Unix timestamp when the log message is no longer valid (it goes purple at this time).
.sp
.BR acktime
-1, or Unix timestamp when an active acknowledgement expires.
.sp
.BR disabletime
-1, or Unix timestamp when the status is no longer disabled.
.sp
.BR sender
IP-address where the status was received from.
.sp
.BR cookie
-1, or the cookie value used to acknowledge an alert.
.sp
.BR "First line of status log"

.IP "hobbitdxboard"
Retrieves an XML-string with the summary of all status logs
as for the "hobbitdboard" command.


.SH EXAMPLE

Send a normal status message to the BBDISPLAY server, using the
standard Hobbit protocol on TCP port 1984:
.br
   $ $BB $BBDISP "status www,foo,com.http green `date` Web OK"

Send the same status message, but using HTTP protocol via the
webservers' bbmessage.cgi script:
.br
   $ $BB http://bb.foo.com/cgi-bin/bbmessage.cgi "status www,foo,com.http green `date` Web OK"

Use "query" message to determine the color of the "www" test, and
restart Apache if it is red:
.br

   $ WWW=`$BB $BBDISP "query www,foo,com.www" | awk '{print $1}'`
   $ if [ "$WWW" = "red" ]; then /etc/init.d/apache restart; fi

Use "config" message to update the local bb-dftab file (but only
if we get a response):
.br

   $ $BB $BBDISP "config bb-dftab" >/tmp/bb-dftab.new
   $ if [ -s /tmp/bb-dftab.new ]; then 
       mv /tmp/bb-dftab.new $BBHOME/etc/bb-dftab
     fi

.SH NOTES
This man-page describes the bb client program provided
as part of Hobbit . This implementation provides features 
not present in the standard Big Brother bb client - 
specifically, the support for sending messages over HTTP, 
and many commands such as "query" and "config" are not part 
of the bb client shipped with Big Brother.

The Hobbit version of the bb client program is compatible
with version 1.9e-BTF of the Big Brother bb client.

.SH "SEE ALSO"
bbcombotest(1), bb-hosts(5), hobbitserver.cfg(5), hobbit(7)

