.TH BBHOSTSHOW 1 "Version 4.2.0:  9 Aug 2006" "Hobbit Monitor"
.SH NAME
bbhostshow \- output the full bb-hosts file
.SH SYNOPSIS
.B "bbhostshow [--bbdisp] [--bbnet] [filename]"

.SH DESCRIPTION
.I bbhostshow(1)
dumps the full bb-hosts file to stdout. It follows "include"
tags in the bb-hosts files, and prints the full contents
as seen by the
.I bbgen(1)
and
.I bbtest-net(1)
utilities.

If no filename is given, bbhostshow displays the file pointed
to by the BBHOSTS environment variable.

.SH OPTIONS
.IP "--bbdisp"
Show the bb-hosts file following include statements as a
BBDISPLAY server would.

.IP "--bbnet"
Show the bb-hosts file following include statements as a
BBNET server would.


.SH ENVIRONMENT VARIABLES
.IP BBHOSTS
Filename for the
.I bb-hosts(5)
file.

.SH "SEE ALSO"
bb-hosts(5), hobbitserver.cfg(5)
