.TH LOGFETCH 1 "Version 4.1.2: 11 Oct 2005" "Hobbit Monitor"
.SH NAME
logfetch \- Hobbit client data collector
.SH SYNOPSIS
.B "logfetch CONFIGFILE STATUSFILE"

.SH DESCRIPTION
\fBlogfetch\fR

.SH FILES
.IP $BBHOME/tmp/logfetch.cfg
.IP $BBHOME/tmp/logfetch.status

.SH "SEE ALSO"
hobbit(7), hobbit-clients.cfg(5)

