.TH BB-CSVINFO.CGI 1 "Version 2.14: 19 Dec 2003" "bbgen toolkit"
.SH NAME
bb-csvinfo.cgi \- CGI program to show host information from a CSV file
.SH SYNOPSIS
.B "bb-csvinfo.cgi"

.SH DESCRIPTION
.I bb-csvinfo.cgi
is invoked as a CGI script via the bb-csvinfo.sh CGI wrapper.
Based on the parameters it receives, it searches a comma-
separated file for the matching host, and presents the information
found as a table.

bb-csvinfo.cgi is passed a QUERY_STRING environment variable 
with the following parameters:

   key (string to search for, typically hostname)
   column (columnnumber to search - default 0)
   db  (name of the CSV database file in $BBHOME/etc/, default hostinfo.csv)
   delimiter (delimiter character for columns, default semi-colon)

CSV files are easily created from e.g. spreadsheets, by exporting them
in CSV format. You should have one host per line, with the first line
containing the column headings. Despite their name, the default delimiter
for CSV files is the semi-colon - if you need a different delimiter, 
invoke bb-csvinfo.cgi with the "delimiter=<character>" in the query
string.

.SH "SEE ALSO"
bb-hosts(5), bb-environ(5)

