.TH BB-FINDHOST.CGI 1 "Version 2.14: 19 Dec 2003" "bbgen toolkit"
.SH NAME
bb-findhost.cgi \- Big Brother CGI script to find hosts
.SH SYNOPSIS
.B "bb-findhost.cgi?host=hostnames"

.SH DESCRIPTION
.I bb-findhost.cgi
is invoked as a CGI script via the bb-findhost.sh CGI wrapper.

bb-findhost.cgi is passed a QUERY_STRING environment variable with the
"host=hostname(s)" parameter. Multiple hostnames can be given, they
should be separated by whitespace.

It then produces a single web page, listing all of the hosts that
matched any of the hostnames, with links to the Big Brother webpages
where they are located.

The matching is case-insensitive. A trailing wildcard is assumed on
all hostnames - e.g. requesting the hostname "www" will match any
host whose name begins with "www".

The output page lists hosts in the order they appear in the
.I bb-hosts(5)
file.

A sample web page implementing the search facility is included
with bbgen, you access it via the URL /bb/help/bb-findhost.html.

.SH "ENVIRONMENT VARIABLES"
.IP BBHOSTS
bb-findhost.cgi uses the BBHOSTS environment variable to find the
bb-hosts file listing all known hosts and their page locations.

.SH "SEE ALSO"
bbgen(1), bb-hosts(5), bb-environ(5)

