.TH HOBBIT-GHOSTS.CGI 1 "Version 4.2:  7 Aug 2006" "Hobbit Monitor"
.SH NAME
hobbit-ghosts.cgi \- CGI program to view ghost clients
.SH SYNOPSIS
.B "hobbit-ghosts.cgi"

.SH DESCRIPTION
\fBhobbit-ghosts.cgi\fR
is invoked as a CGI script via the hobbit-ghosts.sh CGI wrapper.

It generates a listing of the Hobbit clients that have reported data
to the Hobbit server, but are not listed in the
.I bb-hosts(5)
file. Data from these clients - called "ghosts" - are ignored, 
since Hobbit does not know which webpage to present the data on.

The listing includes the hostname that the client reports with, 
the IP-address where the report came from, and how long ago the
report arrived.

By far the most common reason for hosts showing up here is that
the client uses a hostname without a DNS domain, but the bb-hosts
file uses the hostname with the DNS domain. Or vice versa. You can
then use a \fBCLIENT\fR setting in the bb-hosts file to match the
two hostnames together.

.SH OPTIONS
.IP "--env=FILENAME"
Loads the environment defined in FILENAME before executing the CGI script.

.SH "SEE ALSO"
bb-hosts(5), hobbitserver.cfg(5)

