.TH HOBBIT-STATUSREPORT.CGI 1 "Version 4.2: 16 Apr 2006" "Hobbit Monitor"
.SH NAME
hobbit-statusreport.cgi \- CGI program to report a status for a group of servers
.SH SYNOPSIS
.B "hobbit-statusreport.cgi --column=COLUMNNAME [options]"

.SH DESCRIPTION
\fBhobbit-statusreport.cgi\fR is a CGI tool to generate a simple HTML
report showing the current status of a single column for a group of
Hobbit hosts.

E.g. You can use this report to get an overview of all of the SSL 
certificates that are about to expire.

The generated webpage is a simple HTML table, suitable for copying
into other documents or e-mail.

hobbit-statusreport.cgi runs as a CGI program, invoked by your webserver.
It is normally run via a wrapper shell-script in the secured CGI 
directory for Hobbit.

.SH OPTIONS
.IP "--column=COLUMNNAME"
Report the status of the COLUMNNAME column.

.IP "--all"
Report the status for all hosts known to Hobbit. By default,
this tool reports only on the hosts found on the current page
from where the CGI was invoked (by looking at the "pagepath"
cookie).

.IP "--filter=CRITERIA"
Only report on statuses that match the CRITERIA setting. See the
.I bb(1)
man-page - in the "hobbitdboard" command description - for 
details about specifying filters.

.IP "--no-colors"
Do not include text showing the current color of each status in
the report.

.IP "--env=FILENAME"
Load the environment from FILENAME before executing the CGI.

.IP "--area=NAME"
Load environment variables for a specific area. NB: if used,
this option must appear before any --env=FILENAME option.

.SH "SEE ALSO"
hobbit(7)

