.TH XYMONCMD 1 "Version 4.3.22-rc2:  2 Nov 2015" "Xymon"
.SH NAME
xymoncmd \- Run a command under a xymon environment
.SH SYNOPSIS
.B "xymoncmd [options] [COMMAND]"

.SH DESCRIPTION
.I xymoncmd(1)
is a utility that can setup the Xymon environment variables as defined in a 
.I xymonlaunch(8)
compatible environment definition file, and then execute a command
with this environment in place. It is mostly used for testing
extension scripts or in other situations where you need to run
a single command with the environment in place.

COMMAND is the command to execute after setting up the environment. All 
remaining arguments on the command line are passed on to it.

If executed without a COMMAND, it will drop you into an interactive 
subshell with this environment defined globally. If an environment 
file was specified (or was found), then the SHELL variable there 
will be used. If none was present, xymoncmd may inherit the 
$SHELL of its execution environment and use that. If none was found,
xymoncmd will use /bin/sh.


.SH OPTIONS AND PARAMETERS
.IP "\-\-env=ENVFILE"
Points xymoncmd to the file where the environment definitions are to be 
loaded from. If not specified, it will search various locations for 
first a xymonserver.cfg and then a xymonclient.cfg file. On xymon 
servers with both installed, the server environment will be loaded by 
default.

.IP "\-\-debug"
Enable debugging output.

.SH "SEE ALSO"
xymonlaunch(8), xymon(7)

