.TH CLIENTLAUNCH.CFG 5 "Version 4.3.5:  9 Sep 2011" "Xymon"
.SH NAME
clientlaunch.cfg \- Task definitions for the xymonlaunch utility

.SH SYNOPSIS
.B ~xymon/client/etc/clientlaunch.cfg

.SH DESCRIPTION
The clientlaunch.cfg file holds the list of tasks that xymonlaunch runs 
on a Xymon client. This is typically just the Xymon client itself, but
you can add custom test scripts here and have them executed regularly by
the Xymon scheduler.

.SH "FILE FORMAT"
See the
.I tasks.cfg(5)
description.

.SH "SEE ALSO"
xymonlaunch(8), xymon(7)

