.TH CRITICALEDITOR.CGI 1 "Version 4.3.27: 24 Mar 2016" "Xymon"
.SH NAME
criticaleditor.cgi \- Xymon Critical Systems View Editor CGI
.SH SYNOPSIS
.B "criticaleditor.cgi"

.SH DESCRIPTION
\fBcriticaleditor.cgi\fR is invoked as a CGI script via the 
criticaleditor.sh CGI wrapper.

criticaleditor.cgi is a web-based editor for the 
.I critical.cfg(5)
file, which is used to configure the Xymon "Critical Systems" view.

A detailed description of how to use the editor is provided in the
Xymon Web documentation, available from the "Help" \-> "Critical Systems"
link on the Xymon website.

.SH SECURITY
Access to this CGI script should be restricted through access controls
in your webserver. Editing the Critical Systems View configuration will
impact the monitoring of your site.

.SH OPTIONS
.IP "\-\-config=FILENAME"
Name of the Critical Systems View configuration file. The default is
critical.cfg in the $XYMONHOME/etc/ directory.

.IP "\-\-env=FILENAME"
Loads the environment defined in FILENAME before executing the CGI script.

.IP "\-\-area=NAME"
Load environment variables for a specific area. NB: if used,
this option must appear before any \-\-env=FILENAME option.

.IP "\-\-debug"
Enables debugging output.

.SH "SEE ALSO"
criticalview.cgi(1), critical.cfg(5), xymon(7)

