.TH ORCAXYMON 1 "Version 4.3.26: 19 Feb 2016" "Xymon"
.SH NAME
orcaxymon \- Xymon client utility to grab data from ORCA
.SH SYNOPSIS
.B "orcaxymon --orca=PREFIX [options]"

.SH NOTICE
This utility is included in the client distribution for Xymon 4.2.
However, the backend module to parse the data it sends it \fBNOT\fR
included in Xymon 4.2. It is possible to use the generic Xymon
NCV data handler in
.I xymond_rrd(8)
to process ORCA data, if you have an urgent need to do so.

.SH DESCRIPTION
\fBorcaxymon\fR is an add-on tool for the Xymon client. It is 
used to grab data collected by the ORCA data collection tool 
(orcallator.se), and send it to the Xymon server in NCV format.

orcaxymon should run from the client
.I xymonlaunch(8)
utility, i.e. there must be an entry in the 
.I clientlaunch.cfg(5)
file for orcaxymon.

.SH OPTIONS
.IP "--orca=PREFIX"
The filename prefix for the ORCA data log. Typically this is the
directory for the ORCA logs, followed by "orcallator". The actual
filename for the ORCA logs include a timestamp and sequence number, 
e.g. "orcallator-2006-06-20-000". This option is required.

.IP "--debug"
Enable debugging output.

.SH "SEE ALSO"
xymon(7), clientlaunch.cfg(5)

