s!XYMONSERVERHOSTNAME="localhost"!XYMONSERVERHOSTNAME="$CLIENTHOSTNAME"!
s!XYMONSERVERWWWNAME="localhost"!XYMONSERVERWWWNAME="$CLIENTHOSTNAME"!
s!XYMONSERVERIP="127.0.0.1"!XYMONSERVERIP="$XYMONSERVERS"!
