<?

//class ANALYSE extends FPDF
class ANALYSIS extends TCPDF
{

public function Header()
{
    //Logo
    $this->Image('images/logobk.png',10,8,50,'http://www.bluekiwi-software.com/');
    //Saut de ligne
    $this->Ln(10);
    //Police Times gras 15
    $this->SetFont('Times','B',15);
    //Decalage a droite
    $this->Cell(80);
    //Titre
    $this->Cell(120,15,'Analysis of '.$_POST['nom'],0,0,'C');
    $this->Line(20,25,190,25);
    //Saut de ligne
    $this->Ln(20);
}   
    
public function Footer()
{   

   $m=strftime("%m") ;
   $y=strftime("%G") ;

   if (strftime("%d") < 16)
   { 
	$mois = mktime( 0, 0, 0, ($m-1), 1, $y ) ;
	$mois_rap = strftime("%B %G",$mois) ;
	$mois_num = strftime("%m",$mois) ;
   }
   else
   {
	$mois_rap = strftime("%B %G") ;
	$mois_num = strftime("%m") ;
   }

    //Positionnement a 1,5 cm du bas
    $this->SetY(-15);
    //Police Arial italique 8
    $this->Line(20,282,190,282);
    $this->SetFont('Times','BI',8);
    $this->SetX(15);
    $this->Cell(0,10,$mois_rap,0,0,'L');
    //Numero de page
    $this->SetFont('Times','I',8);
    $this->SetX(12);
    $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
    $this->SetFont('Times','BI',9);
    $this->SetX(160);
    $this->Cell(0,10,'Generated by Xymon',0,0,'C');
}

public function Titre($titre)
{
    //Arial 12
    $this->SetFont('Times','B',16);
    //Couleur de fond
    $this->SetFillColor(200,220,255);
    //Titre
    $this->Cell(0,6,"$titre",0,1,'L',1);
    //Saut de ligne
    $this->Ln(4);
}

}

?>
