<?

//
// Declaration of the REPORT class 
//
class REPORT extends TCPDF
{

public function Header()
{   

	//Logo
	$this->Image('images/logobk.png',10,8,50,'http://www.bluekiwi-software.com/');
	//Saut de ligne
	$this->Ln(10);
	//Police Times gras 15
	$this->SetFont('Times','B',15);
	//Decalage a droite
	$this->Cell(80);
	//Titre
	$this->Cell(120,15,'Monitoring Report for '.$_POST['nom'],0,0,'C');
	$this->Line(20,25,190,25);
	//Saut de ligne
	$this->Ln(20);

} // End of header


public function Footer()
{   

	$m=strftime("%m") ;
	$y=strftime("%G") ;
    
	if (strftime("%d") < 16) 
	{
		$mois = mktime( 0, 0, 0, ($m-1), 1, $y ) ;
		$mois_rap = strftime("%B %G",$mois) ;
	}   
	else
	{   
		$mois_rap = strftime("%B %G") ;
	}	   

	//Positionning at 1,5cm from bottom
	$this->SetY(-15);
	//Police Times italique 8
	$this->Line(20,282,190,282);
	$this->SetFont('Times','BI',8);
	$this->SetX(15);

	switch($_POST['chxrap']) 
	{

        	case "daily" :
        	$this->Cell(0,10,strftime("%A %d %B %Y"),0,0,'L');
        	break ;

        	case "weekly" :
        	$semaine1 = strftime("%V") - 1 ;
        	$this->Cell(0,10,'Week '.$semaine1,0,0,'L');
        	break ;

        	case "biweek" :
        	$semaine1 = strftime("%V") - 2 ;
        	$semaine2 = strftime("%V") - 1 ;
        	$this->Cell(0,10,'Weeks '.$semaine1.' - '.$semaine2,0,0,'L');
        	break ;

        	case "monthly" :
        	$this->Cell(0,10,$mois_rap,0,0,'L');
        	break ;

        	case "annual" :
        	$this->Cell(0,10,'Year '.strftime("%G"),0,0,'L');
        	break ;

        	case "dsimensuel" :
        	$this->Cell(0,10,$mois_rap,0,0,'L');
        	break ;

	}

	// Page number
	$this->SetFont('Times','I',8);
	$this->SetX(12);
	$this->Cell(0,10,'Page '.$this->PageNo().'/{nb}' ,0,0,'C');
	$this->SetFont('Times','BI',9);
	$this->SetX(160);
	$this->Cell(0,10,'Generated by Xymon',0,0,'C');

} // End of footer


public function Titre($titre)
{

	//Times 12
	$this->SetFont('Times','B',16);
	//Couleur de fond
	$this->SetFillColor(200,220,255);
	//Titre
	$this->Cell(0,6,"$titre",0,1,'L',1);
	//Saut de ligne
	$this->Ln(4);

} // End of Titre

} // End of class REPORT


?>
