.TH HOBBITLAUNCH 8 "Version 4.2.2: 15 Dec 2008" "Xymon"
.SH NAME
hobbitlaunch \- Master program to launch other Xymon programs

.SH SYNOPSIS
.B "hobbitlaunch [options]"

.SH DESCRIPTION
.I hobbitlaunch(8)
is the main program that controls the execution and scheduling of 
all of the components in the Xymon system.

hobbitlaunch allows the administrator to add, remove or change the set of
Xymon applications and extensions without restarting Xymon -
hobbitlaunch will automatically notice any changes in the set of tasks,
and change the scheduling of activities accordingly.

hobbitlaunch also allows the administrator to setup specific logfiles for
each component of the Xymon system, instead of getting output
from all components logged to a single file.

.SH OPTIONS
.IP "--env=FILENAME"
Loads the environment from FILENAME before starting other tools.
The environment defined by FILENAME is the default, it can be
overridden by the ENVFILE option in 
.I hobbitlaunch.cfg(5)

.IP "--config=FILENAME"
This option defines the file that hobbitlaunch scans for tasks it
must launch. A description of this file is in 
.I hobbitlaunch.cfg(5)
The default tasklist is /etc/hobbitlaunch.cfg

.IP "--log=FILENAME"
Defines the logfile where hobbitlaunch logs information about
failures to launch tasks and other data about the operation of
hobbitlaunch. Logs from individual tasks are defined in the hobbitlaunch.cfg
file. By default this is logged to stdout.

.IP "--pidfile=FILENAME"
Filename which hobbitlaunch saves its own process-ID to. Commonly used by
automated start/stop scripts.

.IP "--verbose"
Logs the launch of all tasks to the logfile. Note that the logfile
may become quite large if you enable this.

.IP "--dump"
Just dump the contents of the hobbitlaunch.cfg file after parsing it.
Used for debugging.

.IP "--debug"
Enable debugging output while running.

.IP "--no-daemon"
hobbitlaunch normally detaches from the controlling tty and runs as a
background task. This option keeps it running in the foreground.

.SH STARTING TASKS
hobbitlaunch will read the configuration file and start all of the tasks
listed there.

If a task completes abnormally (i.e. terminated by a signal or with
a non-zero exit status), then hobbitlaunch will attempt to restart it
5 times. If it still will not run, then the task is disabled for 10
minutes. This will be logged to the hobbitlaunch logfile.

If the configuration file changes, hobbitlaunch will re-read it and 
notice any changes. If a running task was removed from the configuration,
then the task is stopped. If a new task was added, it will be started.
If the command used for a task changed, or it was given a new environment
definition file, or the logfile was changed, then the task is stopped
and restarted with the new definition.

.SH "SEE ALSO"
hobbitlaunch.cfg(5), xymon(7)

