.TH CRITICALVIEW.CGI 1 "Version 4.3.13:  7 Jan 2014" "Xymon"
.SH NAME
criticalview.cgi \- Xymon Critical Systems view CGI
.SH SYNOPSIS
.B "criticalview.cgi"

.SH DESCRIPTION
\fBcriticalview.cgi\fR is invoked as a CGI script via the 
criticalview.sh CGI wrapper.

criticalview.cgi matches the current critical statuses against the
.I critical.cfg(5)
file, and generates the "Critical Systems" view. 

.SH RELATION TO OLD CRITICAL PAGE
This view is a replacement for the statically generated "critical" page 
provided in versions of Xymon prior to version 4.2. Although the 
"critical" pages are supported throughout Xymon 4.x, it is recommended 
that You switch to the newer Critical Systems view provided by this CGI.

.SH OPTIONS
.IP "--acklevel=NUMBER"
Sets the acknowledgment level for acknowledgments sent via the
.I ackinfo.cgi(1)
page. Note that this may be overridden by the configuration of the
ackinfo.cgi utility.

.IP "--tooltips"
Hide the host description in a "tooltip", i.e. it will be shown when your
mouse hovers over the hostname on the webpage. This saves space on the 
display so there is more room for the status columns.

.IP "--hffile=PREFIX"
Define the header/footer files used when building the webpage. The actual
files used will be PREFIX_header and PREFIX_footer found in the ~xymon/server/web/ 
directory. Default: critical.

.IP "--env=FILENAME"
Loads the environment defined in FILENAME before executing the CGI script.

.IP "--area=NAME"
Load environment variables for a specific area. NB: if used,
this option must appear before any --env=FILENAME option.

.IP "--debug"
Enables debugging output.

.IP "--config=FILENAME"
Use FILENAME as the configuration file for the Critical 
Systems information. The default is to load this from
$XYMONHOME/etc/critical.cfg

.IP "--config=ID:FILENAME
Allows the use of multiple Critical Systems configuration files
on a single webpage. "ID" is a text that will be shown on the web
page prior to the critical systems from FILENAME. This option can be
repeated to include critical systems from multiple configurations.

.SH "ENVIRONMENT VARIABLES"
.IP XYMONHOME
Used to locate the template files for the generated web pages.

.IP QUERY_STRING
Contains the parameters for the CGI script.

.SH "SEE ALSO"
ackinfo.cgi(1), xymon(7)

